### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by mplescano** [joao-osilva/rabbitmq-cluster-docker-compose#1]
Hi:

I think it's missing these files in your repo:
$PWD/storage/rabbitmq-node-1
$PWD/storage/rabbitmq-node-2
$PWD/storage/rabbitmq-node-3

can you provide them?

Regards

**Comment by joao-osilva** [comment]
They are not files, they are the paths in which the volume will be mounted at the host. You can change it to another path if you like.
